export * from './user.service';
export * from './platform.service';
export * from './developer.service';
export * from './publisher.service';
export * from './region.service';
export * from './dateType.service';
export * from './genre.service';
export * from './game.service';
export * from './favourite.service';
export * from './library.service';
export * from './review.service';
export * from './recommendation.service';
export * from './playStatus.service';
export * from './home.service';
export * from './forums/tag.service'
export * from './forums/discussion.service'
export * from './forums/post.service'
export * from './release.service';
